config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tweets, only: [:index, :show] do
    resources :replies, only: [:create]
  end

  root to: 'tweets#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to :tweet
  belongs_to :user

end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  has_many :replies

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :replies
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  before_action :authenticate_user!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @reply = @tweet.replies.build(reply_params)
    @reply.user = current_user
    if @reply.save
      TweetMailer.new_reply(@reply).deliver_later
      redirect_to tweet_path(@tweet)
    else
      render 'tweets/show'
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.order(created_at: :asc)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @replies = @tweet.replies
    @reply = Reply.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstructionalTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path, class: "navbar-link" %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "navbar-link" %></li>
          <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "navbar-link" %></li>
          <li><%= link_to 'Log In', new_user_session_path, class: "navbar-link" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

  </body>
</html>

app/views/tweets/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <% @tweets.each do |tweet| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong><%= tweet.user.email %></strong>
            <%= link_to "Replies (#{tweet.replies.count})", tweet_path(id: tweet.id), class: 'pull-right' %>
          </div>
          <div class="panel-body">
            <%= tweet.body %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <h3><%= @tweet.user.email %></h3>
      <div class="well">
        <p><%= @tweet.body %></p>
      </div>

      <% @replies.each do |reply| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong><%= reply.user.email %></strong>
          </div>
          <div class="panel-body">
            <%= reply.body %>
          </div>
        </div>
      <% end %>

      <div class="form-group text-center">
        <%= form_for @reply, url: tweet_replies_path(tweet_id: @tweet.id), method: :post do |f| %>
          <%= f.text_area :body, class: 'form-control' %>
          <%= f.submit 'Post a reply', class: 'btn btn-default' %>
        <% end %>

      </div>

    </div>
  </div>
</div>